apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: devonchou/event-booking-db:v1
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-data
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "testdb"
            - name: MYSQL_USER
              value: "testuser"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-user-pass
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-root-pass
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: db-data
          awsElasticBlockStore:
            volumeID: vol-0a14d9ba76a91c99f
            fsType: ext4
      initContainers:
        - name: busybox
          image: busybox:latest
          args: ["rm", "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
